

default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: heroku_test_dev
  host: localhost
  username: postgres
  password: root
  encoding: unicode
  
test:
  <<: *default
  database: heroku_test_test
  host: localhost
  username: postgres
  password: root
  encoding: unicode

production:
  <<: *default
  database: heroku_test_prod
