

default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: playground_dev
  host: localhost
  username: postgres
  password: root
  encoding: unicode

test:
  <<: *default
  database: playground_test
  host: localhost
  username: postgres
  password: root
  encoding: unicode

production:
  <<: *default
  database: playground_prod
